Plants config release/103
Ensembl/ensembl-compara pull request #230
Opened 2020-09-14 15:57 UTC by brunocontrerasmoreira

## Description

Hi @CristiGuijarro @dthybert @gnaamati  @marcoooo @james-monkeyshines these are the updated config files for Plants Compara for release 103. 

We have updated the species tree, 

- renaming two species which are now strains sets as explained on ticket https://www.ebi.ac.uk/panda/jira/browse/ENSINT-518 (panicum and theobroma)
- adding five new species, including a tetraploid (arachis)

We have also updated the allowed species files, removing some species to make room for the new ones. I am afraid we will do this for the next few releases. 

Let me know if this is ok with Compara,
Bruno

2020-09-15 12:53 UTC, CristiGuijarro commented
`hordeum_vulgare_goldenpromise
ostreococcus_lucimarinus
panicum_hallii_fil2
prunus_avium
theobroma_cacao_criollo`

Have all been removed from the allowed species file, but remain in the species tree -  I am not sure that this won't break something somewhere in either the pipelines or later display?

2020-09-15 13:01 UTC, brunocontrerasmoreira commented
I don't know either @CristiGuijarro . This is the first release we edit this file, we'll follow your recommendations

2020-09-15 13:04 UTC, CristiGuijarro commented
It might be fine, @JAlvarezJarreta has told me this (and I quote directly):

> for e102 we had species in the species tree that we didn't include in our database and everything was working fine

2020-09-16 17:16 UTC, muffato commented on conf/plants/species_tree.topology.nw
> +            arachis_hypogaea_B,
Currently all polyploids are also in the species tree "on their own". Can you add `arachis_hypogaea` too ?

2020-09-16 21:52 UTC, muffato requested changes
There is a syntax error in the JSON file that needs to be fixed, and I would like `arachis_hypogaea` to be in the species tree on its own

2020-09-16 21:52 UTC, muffato commented on conf/plants/allowed_species.json
> +    "chenopodium_quinoa"
Missing comma
```suggestion
    "chenopodium_quinoa",
```

2020-09-17 09:33 UTC, muffato approved these changes

2020-09-21 08:57 UTC, CristiGuijarro approved these changes

2020-09-21 11:50 UTC, dthybert commented
arachis_hypogaea is a tetraploid so it means that we will be at 101 haploid genomes and not 100. Could you please remove one diploid species from the set to stay at 100?

2020-09-21 12:01 UTC, muffato commented
FYI the current count of haploid genomes is 104, not 100

2020-09-21 12:21 UTC, brunocontrerasmoreira commented
Done, I've removed one more

2020-09-21 13:19 UTC, muffato commented
Sorry, 102, not 104. (in `ensembl_compara_plants_49_102`)

2020-09-21 13:31 UTC, brunocontrerasmoreira commented
Thanks @muffato , does that include outgroups? Can't we leave like that?

2020-09-21 13:38 UTC, dthybert commented
> Thanks @muffato , does that include outgroups? Can't we leave like that?

100 is just for plant so you can leave as it is.

2020-09-21 22:07 UTC, merged