Add (many) more checks on imported homologies
Ensembl/ensembl-compara pull request #275
Opened 2021-04-07 16:17 UTC by carlacummins

## Description

Checks on homology imports have not gone beyond basic row counting. In e104, several truncated rows were discovered, which were not being detected by that check. I have added a check on all fields in both `homology` and `homology_member` tables. This includes checking the min, max and avg values for each column, in order to try to detect truncated values.

**Related JIRA tickets:**
- ENSCOMPARASW-4296

## Overview of changes
- stats from each field are collected from each row of the flatfile to form a hash of expected values
- comparison of counts and range stats are performed for each field
- if there's a failure, a small report will be printed
- if there's a failure, the import will be automatically retried in `REPLACE INTO` mode

## Testing
- testing was done using a homology dump file from e104 (truncated to 200 lines) and a `standaloneJob.pl`
- I added some code just before the HC was run to pause execution in order to give me time to go mess up the database to simulate: (a) missing complete rows, (b) missing some fields from some rows, (c) truncated values in some rows
- in all cases, it was detected by the HC and handled accordingly
- the reimport with `REPLACE` always fixed the issue I had introduced

## Notes
Regarding floating point numbers : I could have used `ROUND` or `FLOOR` or something in my SQL commands, but since rounding of numbers can be done in so many different ways, I thought it was safest to let Perl do all rounding using `sprintf` - at least this way all numbers will be treated in the same way.

2021-04-07 17:01 UTC, JAlvarezJarreta requested changes
Just a few lines of code, but now we are certain we won't need to deal with more annoying issues in the homology import :tada:

2021-04-07 17:01 UTC, JAlvarezJarreta commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +    } elsif ( $exp_vals->{min_id} != $db_vals->{min_id} || $exp_vals->{max_id} != $exp_vals->{max_id} || $exp_vals->{avg_id} != $db_vals->{avg_id} ) {
```suggestion
    } elsif ( $exp_vals->{min_id} != $db_vals->{min_id} || $exp_vals->{max_id} != $db_vals->{max_id} || $exp_vals->{avg_id} != $db_vals->{avg_id} ) {
```

2021-04-07 17:01 UTC, JAlvarezJarreta commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +    } elsif ( $exp_vals->{min_pos} != $db_vals->{min_pos} || $exp_vals->{max_pos} != $exp_vals->{max_pos} || $exp_vals->{avg_pos} != $db_vals->{avg_pos} ) {
```suggestion
    } elsif ( $exp_vals->{min_pos} != $db_vals->{min_pos} || $exp_vals->{max_pos} != $db_vals->{max_pos} || $exp_vals->{avg_pos} != $db_vals->{avg_pos} ) {
```

2021-04-08 08:33 UTC, carlacummins commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +    } elsif ( $exp_vals->{min_stn} != $db_vals->{min_stn} || $exp_vals->{max_stn} != $exp_vals->{max_stn} || $exp_vals->{avg_stn} != $db_vals->{avg_stn} ) {
Well spotted 👍

2021-04-08 08:35 UTC, carlacummins commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +        unless $exp_vals->{min_gtr} == $db_vals->{min_gtr} && $exp_vals->{max_gtr} == $exp_vals->{max_gtr} && $exp_vals->{avg_gtr} == $db_vals->{avg_gtr};
Ah - this one needs to return a `0` too. Obv missed it when I reformatted all the others. Thanks.

2021-04-08 08:35 UTC, carlacummins commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +    my $homology_id_end   = $homology_id_start + $total_rows - 1; # TODO: do we need -1?
Yes, we do 😄

2021-04-08 08:36 UTC, carlacummins commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +    } elsif ( $exp_vals->{min_cov} != $db_vals->{min_cov} || $exp_vals->{max_cov} != $exp_vals->{max_cov} || $exp_vals->{avg_cov} != $db_vals->{avg_cov} ) {
The perils of copy-paste 😓

2021-04-08 16:07 UTC, JAlvarezJarreta approved these changes

2021-04-08 16:11 UTC, carlacummins commented on modules/Bio/EnsEMBL/Compara/RunnableDB/Flatfiles/MySQLImportHomologies.pm
> +        die "Import failed 20 times in a row... Something else must be wrong\n" if $num_tries > 20;
Yes, let's reduce to 10 - I just randomly picked 20.

```suggestion
        die "Import failed 10 times in a row... Something else must be wrong\n" if $num_tries > 10;
```

2021-04-08 16:11 UTC, merged