Bugfix/duplicate jira blocker links
Ensembl/ensembl-compara pull request #299
Opened 2021-06-18 14:07 UTC by awgymer

## Description

When using the --update flag, tickets are reopened if they already exist. However, the blocker link that is created against the 'Handover of release DB' ticket is created again, resulting in duplicate links. Update the script : don't add a new link if it already exists.

**Related JIRA tickets:**
- ENSCOMPARASW-4300

## Overview of changes

#### Change 1
- Added  a `get_ticket` method to `JIRA.pm` which returns the JSON representation of a JIRA ticket from the API endpoint `GET /rest/api/3/issue/{issueIdOrKey}`

#### Change 2
- In `link_tickets` use the issue JSON for the inward ticket to look for `issuelinks` and check for any exisiting link with the same `name` and `outwardIssue` `key`

## Testing
`create_datacheck_tickets.pl` run on `/hps/nobackup2/production/ensembl/jalvarez/metazoa_datachecks_104/tapfile/ForeignKeysCompara.tap` against release `104`.

2021-06-21 14:52 UTC, JAlvarezJarreta requested changes
Only the variable renaming is required, the other two are just comments/suggestions. Nice touch with the new function :+1:

2021-06-21 14:52 UTC, JAlvarezJarreta commented on modules/Bio/EnsEMBL/Compara/Utils/JIRA.pm
> +            if ($i->{type}->{name} eq $link_type && $i->{outwardIssue}->{key} eq $outward_key) {
`$i` is not great for readability:
```suggestion
        foreach my $link ( @{$inward_ticket->{issuelinks}} ){
            if ($link->{type}->{name} eq $link_type && $link->{outwardIssue}->{key} eq $outward_key) {
```

2021-06-21 14:52 UTC, JAlvarezJarreta commented on modules/Bio/EnsEMBL/Compara/Utils/JIRA.pm
> +        my $link_exists = 0;
Just a comment: in Perl, the result of `my $link_exists;` and this line is exactly the same.

2021-06-21 14:52 UTC, JAlvarezJarreta commented on modules/Bio/EnsEMBL/Compara/Utils/JIRA.pm
> +        if ( $link_exists == 1 ) {
As a suggestion, the following does exactly the same:
```suggestion
        if ( $link_exists ) {
```

2021-06-21 15:36 UTC, CristiGuijarro reviewed
Approved on the basis that this has been tested and works - although I haven't "seen" any noise in the slack channel?
Would also like to see the `$link_exists` check rewritten to remove the additional complexity/ make it more concise.
`if ( $inward_ticket ) { ...`

2021-07-09 15:25 UTC, awgymer commented on modules/Bio/EnsEMBL/Compara/Utils/JIRA.pm
> +        }
Ah I see what was meant now!

2021-07-09 15:44 UTC, JAlvarezJarreta approved these changes
The Travis failure is not related with this PR (and it has been fixed in the target branch), so it can be merged :+1:

2021-07-09 16:52 UTC, merged