Examples related to the Pythonistas presentation on pytest
Ensembl/ensembl-compara pull request #395
Opened 2022-01-28 13:28 UTC by ipilizota

* A file with the code I presented
* A file with more examples

They will be referenced in the presentation & alongside the presentation on Confluence.
The idea is to use them as templates for future tests. 

Making  a PR so we're sure this is where they should go.
And to hear what Travis thinks about them, of course.

2022-02-02 12:08 UTC, JAlvarezJarreta requested changes
The workaround that Thomas did to import these scripts may be quite hard to understand/follow to many people, but I still need some more time to prepare and present an alternative to this.

I have checked mainly the docstrings to ensure readibility, as I expect the rest to be as good as it was in the original branch :) The only other change I would propose is `unit_tests` instead of `unittests` in the folder name, to make it even more clear what we are talking about.

2022-02-02 12:08 UTC, JAlvarezJarreta commented on src/python/examples/unittests/test_orthology_benchmark.py
> +            species_list: A list of species (genome names).
```suggestion
            core_list: A list of core database names.
```

2022-02-02 12:08 UTC, JAlvarezJarreta commented on src/python/examples/unittests/test_data_dumps.py
> +            species_list: A list of species (genome names).
```suggestion
            core_list: A list of core db names.
```

2022-02-02 12:08 UTC, JAlvarezJarreta commented on src/python/examples/unittests/test_data_dumps.py
> +            expectation: Context manager for the expected exception, i.e. the test will only pass if that
```suggestion
            id_type: Type of identifier to use in the dumps.
            expectation: Context manager for the expected exception, i.e. the test will only pass if that
```

2022-02-07 11:48 UTC, twalsh-ebi reviewed
I'll defer to @JAlvarezJarreta on the question of where these examples should go.

In terms of the code itself, I just have a couple of suggestions.

2022-02-07 11:48 UTC, twalsh-ebi commented on src/python/examples/unittests/test_data_dumps.py
> +            ) == "mus_musculus_core_52_105_3"
I think assigning to a `core_names` variable makes it easier to compare this to the parametrised version of the test:
```suggestion
    core_names = ["mus_musculus_core_105_1", "mus_musculus_core_52_105_3", "mus_musculus_core_104_4"]
    assert data_dumps.find_latest_core(core_names) == "mus_musculus_core_52_105_3"
```

2022-02-07 11:48 UTC, twalsh-ebi commented on src/python/examples/unittests/test_data_dumps.py
> +                                             self.host, self.port, "/compara", "protein")
I'd be wary of assuming that a path does not exist in the root directory, but if it must be done, I'd suggest at least renaming it to make its purpose clear: 
```suggestion
                                             self.host, self.port, "/nonexistent/path", "protein")
```

2022-02-07 11:48 UTC, twalsh-ebi commented on src/python/examples/unittests/test_orthology_benchmark.py
> +                                             self.host, self.port, "/compara", "protein")
As above, I'd suggest at least renaming the nonexistent path to be as explicit as possible about its purpose:
```suggestion
        with raises(OSError, match=r"Failed to create '/nonexistent/path/default' directory."):
            orthology_benchmark.dump_genomes(["mus_musculus", "naja_naja"], "default",
                                             self.host, self.port, "/nonexistent/path", "protein")
```

2022-02-14 11:49 UTC, ipilizota commented
All suggestions accepted.

2022-02-14 12:07 UTC, ipilizota commented
Travis is failing due to reasons not related to this PR.

2022-02-14 12:17 UTC, twalsh-ebi approved these changes

2022-02-17 12:09 UTC, JAlvarezJarreta approved these changes

2022-02-17 12:51 UTC, merged