Compara is taking back Flatfile Dumps for a release or few
Ensembl/ensembl-compara pull request #428
Opened 2022-05-06 16:03 UTC by CristiGuijarro

## Description

Compara is taking back FTP dumps.

**Related JIRA tickets:**
- ENSCOMPARASW-5413

## Overview of changes
Stuck the json blocks in for the tickets required for running dumps, split into two subtasks - the copy back of the db, and then the running of the pipeline/dumps.

## Testing
This is totally untested.

## Notes
I did change the case for one character in the pan file that was outside of the scope. This was intentional, and I think it should be agreeable.

2022-05-09 17:09 UTC, ipilizota approved these changes
This is looking good to me 👍

2022-05-11 11:32 UTC, twalsh-ebi requested changes
I've only made one suggestion to fix a broken anchor link, but other than that it looks good to go.

2022-05-11 11:32 UTC, twalsh-ebi commented on conf/vertebrates/jira_recurrent_tickets.json
> +            "description": "https://www.ebi.ac.uk/seqdb/confluence/display/EnsCom/Flat+file+dumps#Flatfiledumps- Databaseupdate",
Not the end of the world to leave it as it is, but removing the space from the link will save a moment for the Vertebrates relco:
```suggestion
            "description": "https://www.ebi.ac.uk/seqdb/confluence/display/EnsCom/Flat+file+dumps#Flatfiledumps-Databaseupdate",
```

2022-05-11 12:19 UTC, twalsh-ebi approved these changes

2022-05-11 14:00 UTC, merged