cigar manipulation function
Ensembl/ensembl-compara pull request #435
Opened 2022-05-13 15:09 UTC by dthybert

## Description

This is a same than for the #420. 

When trying solving travis issue with Thiago we merged by error. So this is a second PR taking into account Botond suggestions which was typo correction.

2022-05-19 15:15 UTC, ens-sb approved these changes

2022-05-20 15:20 UTC, twalsh-ebi reviewed
I've added some comments/suggestions here and some in PR #420.

2022-05-26 09:00 UTC, twalsh-ebi requested changes
This is just a quick first pass on the revised changes. I will follow up with a full review.

2022-05-26 15:29 UTC, twalsh-ebi reviewed
It's looking well, and I've just added a last few minor comments.

Though not apparent in #435, I noticed a typo in #420, which can be seen in the license text on [line 5 of the CIGAR module](https://github.com/Ensembl/ensembl-compara/blob/ae7c5ad9c0d9d9fc7c7db82b2c2d792e0eda830d/src/python/lib/ensembl/compara/utils/cigar.py#L5), and which causes the license text to differ from the examples given in the [Ensembl docs on including the Apache 2.0 license in code](https://www.ebi.ac.uk/seqdb/confluence/display/ENS/Ensembl+Software+License#EnsemblSoftwareLicense-Apache2.0LicenseinCode). Please consider changing the license text to match the recommended text.

2022-06-13 10:41 UTC, dthybert commented on src/python/lib/ensembl/compara/utils/cigar.py
>      This function will convert a position at the coordinate level to the sequence level. To be able to
yes

2022-06-14 15:18 UTC, twalsh-ebi reviewed
It's looking grand now. I just have one suggestion (in three comments) to be unambiguous about the members in the `cigar` module being functions rather than methods.

2022-06-14 15:18 UTC, twalsh-ebi commented on src/python/tests/test_cigar.py
> +        """Tests :meth:`cigar.aligned_seq_to_cigar()` function.
```suggestion
        """Tests :func:`cigar.aligned_seq_to_cigar()` function.
```

2022-06-14 15:18 UTC, twalsh-ebi commented on src/python/tests/test_cigar.py
> +        """Tests :func:`cigar.alignment_to_seq_coordinate()` method.
```suggestion
        """Tests :func:`cigar.alignment_to_seq_coordinate()` function.
```

2022-06-14 15:18 UTC, twalsh-ebi commented on src/python/tests/test_cigar.py
>          """Tests :meth:`cigar.aligned_seq_to_cigar()` method.
```suggestion
        """Tests :func:`cigar.aligned_seq_to_cigar()` function.
```

2022-06-17 15:46 UTC, merged