adding thread parameter to CAFE
Ensembl/ensembl-compara pull request #611
Opened 2023-05-11 09:38 UTC by thiagogenez

## Description

Enabling multi-core CAFE runs. 

**Related JIRA tickets:**
- [ENSCOMPARASW-XXXX](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-6465)

## Overview of changes

Default CAFE jobs are configured to use the `1Gb_8c_job` resource class, while highmem CAFE jobs use the `4Gb_48c_job` resource class.

## Testing
Not yet. The test will soon be performed with the plants' protein tree pipeline along with other code updates. 

For code reviewers: [code review SOP](https://www.ebi.ac.uk/seqdb/confluence/display/EnsCom/Code+review+SOP)

2023-05-11 11:51 UTC, twalsh-ebi commented
Thanks for this, @thiagogenez . Can you please submit this against the `main` branch, as resource classes `1Gb_8c_job` and `4Gb_48c_job` do not exist on `release/110`.

2023-05-12 14:23 UTC, ens-sb approved these changes

2023-05-12 15:50 UTC, thiagogenez commented
> Thanks for this, @thiagogenez . Can you please submit this against the `main` branch, as resource classes `1Gb_8c_job` and `4Gb_48c_job` do not exist on `release/110`?

Done. Thanks for letting me know

2023-05-16 12:12 UTC, twalsh-ebi requested changes
Thanks @thiagogenez. These changes look good to me and I'll be happy to approve on the basis that this will be tested before use in production.

I just have one suggestion: could you remove [this CAFE_analysis_himem pipeline tweak](https://github.com/Ensembl/ensembl-compara/blob/5ee41ebddc7815cdeb3599c4321a9cd1628bc8fc/modules/Bio/EnsEMBL/Compara/PipeConfig/Plants/ProteinTrees_conf.pm#L130) as it is no longer needed?

2023-05-16 12:38 UTC, twalsh-ebi approved these changes

2023-05-16 13:31 UTC, merged