The intentions output is now in JSON format with included text summary
Ensembl/ensembl-compara pull request #697
Opened 2023-11-21 14:38 UTC by ens-sb

## Description
The intentions file created during the population of the new release databases should be generated in a human- and machine-readable format such as JSON or YAML, so that we have the option to load the release intentions using a mode of access (e.g. terminal, script or Jupyter notebook) that makes it feasible to focus on the relevant changes, and also to do checks in an automated or semi-automated way.

**Related JIRA tickets:**
- ENSCOMPARASW-7012

## Overview of changes

#### Change 1
The populate_new_database.pl intentions output is now in JSON format with included text summary.

## Testing
The changes were tested on a freshly created 113 plants release database.

---

For code reviewers: [code review SOP](https://www.ebi.ac.uk/seqdb/confluence/display/EnsCom/Code+review+SOP)

2023-11-29 17:52 UTC, Simarpreet-Kaur-Bhurji approved these changes

2024-01-03 09:28 UTC, twalsh-ebi requested changes

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "GenomeDB entries to be copied:\n";
I would suggest to remove the legacy output altogether, as it duplicates the JSON output, and would be harder to work with than the JSON output.
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +        $out .= "\t".$genome_db->dbID.": ".$genome_db->_get_unique_name."\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "MethodLinkSpeciesSet entries to be copied:\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +        $out .= "\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "Additional SpeciesSet entries to be copied:\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +        $out .= "\t".$ss->dbID.": ".join(', ', map { $_->_get_unique_name} @{$ss->genome_dbs})."\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "\nSummary:\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "\t" . scalar(@$all_default_genome_dbs) . " GenomeDBs\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "\t" . scalar(@$all_default_method_link_species_sets) . " MethodLinkSpeciesSets\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= sprintf("\t\t%5d %s\n", $counts{$_}, $_) for sort keys %counts;
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +    $out .= "\t" . scalar(@$all_default_species_sets) . " SpeciesSets\n";
If removing legacy output:
```suggestion
```

2024-01-03 09:28 UTC, twalsh-ebi commented on scripts/pipeline/populate_new_database.pl
> +          ];
If removing legacy output:
```suggestion
    my $out_json = {
              "summary" => $summary, "additional_copied" => $additional,
              "copied_mlss" => $copied_mlss_all, "copied_genome_db" => $copied_genome_db
          };
```

2024-01-03 11:16 UTC, twalsh-ebi approved these changes

2024-01-03 11:18 UTC, merged