Jalvarez/metazoa e114
Ensembl/ensembl-compara pull request #830
Opened 2024-09-02 14:23 UTC by JAlvarezJarreta

## Description

Updates for all 3 gene trees planned for e114, as discussed during the past few months, due to the update of _Drosophila melanogaster_. We have also taken the opportunity to reduce the overlap between metazoa/protostomes and insects collection, leaving only _D. melanogaster_ as the single species overlap.

**Related JIRA tickets:**
- ENSINT-1910
- ENSINT-1911

## Note
Not sure why the insects collection is flagged entirely as changed, as only a total of about 5 species have changes.

2024-09-02 14:46 UTC, vsitnik commented on conf/metazoa/mlss_conf.xml
> +      <genome name="acromyrmex_echinatior_gca000204515v1rs">
no closing `/` . is it as expected?

2024-09-02 14:48 UTC, vsitnik requested changes
I think, we miss a closing `/`  in the xml part.

2024-09-02 14:51 UTC, JAlvarezJarreta commented on conf/metazoa/mlss_conf.xml
> +      <genome name="zootermopsis_nevadensis">
🤦‍♂️ thank you!

2024-09-02 14:56 UTC, vsitnik approved these changes
Thank you!

2024-09-02 15:03 UTC, vsitnik commented on conf/metazoa/mlss_conf.xml
> +      <genome name="zootermopsis_nevadensis">
Thank you, @twalsh-ebi!

2024-09-04 12:46 UTC, Simarpreet-Kaur-Bhurji approved these changes

2024-09-04 12:51 UTC, merged